# Generated by Django 3.1.4 on 2021-01-21 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('r_num', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=50)),
                ('request_address', models.CharField(max_length=100)),
                ('request_size', models.IntegerField()),
                ('request_date', models.DateField()),
                ('request_level', models.BooleanField(default=False)),
                ('request_memo', models.TextField()),
                ('admin_memo', models.TextField(default='')),
                ('read_password', models.CharField(max_length=50)),
                ('read_check', models.IntegerField(default=1)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('scope', models.IntegerField(default=5)),
                ('review_value', models.TextField()),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.request')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.BooleanField(default=False)),
                ('item2', models.BooleanField(default=False)),
                ('item3', models.BooleanField(default=False)),
                ('item4', models.BooleanField(default=False)),
                ('item5', models.BooleanField(default=False)),
                ('item6', models.BooleanField(default=False)),
                ('item7', models.BooleanField(default=False)),
                ('item8', models.BooleanField(default=False)),
                ('item9', models.BooleanField(default=False)),
                ('item10', models.BooleanField(default=False)),
                ('item11', models.BooleanField(default=False)),
                ('item12', models.BooleanField(default=False)),
                ('r_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.request')),
            ],
            options={
                'db_table': 'request_item',
            },
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.BooleanField(default=False)),
                ('item2', models.BooleanField(default=False)),
                ('item3', models.BooleanField(default=False)),
                ('item4', models.BooleanField(default=False)),
                ('item5', models.BooleanField(default=False)),
                ('r_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.request')),
            ],
            options={
                'db_table': 'constructions',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('reply_value', models.TextField()),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.request')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
