# Generated by Django 3.1.4 on 2021-01-13 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='read_check',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('scope', models.IntegerField(default=5)),
                ('review_value', models.TextField()),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.request')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
